# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161215_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254),
        ),
    ]
