# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('link', models.CharField(max_length=1000)),
                ('photos', models.CharField(max_length=1000)),
            ],
        ),
    ]
