# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
    ]
