# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_remove_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='photos',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
